package.json, table.css.scss, table.scss, test/table.html, test/table.rtl.html, test/test.scss
Abstracted the different uses of colors into variables. 
Updated active, selected and active-selected states. 
Updated to follow general vui convention around states being applied to rows:
- Selected state ```<tr class="vui-selected">...</tr>```
- Active state ```<tr class="vui-active">...</tr>```
- Active selected state ```<tr class="vui-active vui-selected">...</tr>```
Moved hover state of table body rows into its own mixin vui-table-rows-selectable, ```<table class="vui-table  vui-table-rows-selectable">...</table>```
=> New colors active selected states

README.md, package.json
=> Rename valence-ui-table to d2l-table-ui

table.scss
=> Fix case when right corner is sharp in rtl if there is one element

d2l-table-style.html, d2l-table-wrapper.html, d2l-table.html, test/d2l-table-wrapper.html
Reopened after moving branch to origin from https://github.com/Brightspace/d2l-table-ui/pull/40
https://rally1.rallydev.com/#/61540980786d/detail/task/63148605368
=> TA104714 - Experiment move styles

bower.json, d2l-scroll-wrapper.html, d2l-sticky-element.html, d2l-table-style.html, d2l-table-wrapper.html, demo/d2l-scroll-wrapper.html, package.json, table.gspec, test/d2l-scroll-wrapper.html
https://rally1.rallydev.com/#/61540980786d/detail/userstory/62024818814
=> US76170 - Add d2l-sticky-element for scroll buttons

d2l-scroll-wrapper.html
=> Fix action buttons being disabled in chrome with dir=rtl

d2l-table-style.html, d2l-table-wrapper.html, d2l-table.html
* Maintaining them in d2l-table-wrapper is becoming unweildy
=> Move table styles back to table

d2l-scroll-wrapper.html, test/d2l-scroll-wrapper.html
* This isn't the most important feature, and probably is better
implemented elsewhere
=> Avoid invalidation when tabIndex is set

d2l-table-wrapper.html, d2l-table.html, test/d2l-table-wrapper.html
Probably should have been done in #100. Oh well
=> Remove references to focused attributes

d2l-table-style.html
https://rally1.rallydev.com/#/87829734000/detail/defect/92940705544
=> Fix leaky styles

bower.json, table.test.js, wct.conf.json
=> remove firefox from test browsers

bower.json, d2l-scroll-wrapper.html, d2l-table-style.html, demo/simple.html
OutOfMemoryError. Return code 0. :confounded:
=> Replace *-child with *-of-type

d2l-table-style.html
- Combine similar selectors
- Add missing selector for rtl selected
- Add missing comma
=> Fix missing selected border colors

d2l-table-style.html, demo/sticky-headers.html
https://rally1.rallydev.com/#/15545269080/detail/task/208493615864
=> remove bottom border from inner table

d2l-scroll-wrapper.html, d2l-table-circle-button.html, test/acceptance/table.gspec
This is part of the process to remove icon-button. This usage can't be replaced with a subtle button.
=> remove icon-button, replace with d2l-table-circle-button

d2l-table-style.html
=> Add a less specific background rule for inheriting background color (for

d2l-tspan.html
Updating criterion feedback UI for rubrics. Need to change table border on hover and focus. Cannot use hover and focus selectors since another component (input-textarea) is focused for input.
=> Add custom border option

package-lock.json, package.json
* Was causing confusion in npm install causing the package to be installed multiple times
=> Fix resize-aware dependency

d2l-table-style.js
=> fix: reverting changes to z-index

.github/workflows/release.yml
Tried releasing from the maintenance branch and realized it's not set up to do so. 🤦
=> allow releasing from release branches

d2l-scroll-wrapper.js
The last usage in Mr. Table has been removed, so this can go now too!
=> removing scroll-wrapper-inner mixin
