- package.json
- table.scss
- test/table.html
- test/table.rtl.html
The bottom rounded corners were not being applied when a table only has the thead element.
> Fix rounded corners for tables with only the thead element

- d2l-table-style.html
- demo/reset.html
- demo/simple-demo.html
There are a few ways of fixing this issue:
1. Set border-collapse property to !important
2. Set border-collapse property in d2l-table-wrapper
3. Move all styles to d2l-table-wrapper. I was thinking of doing this
already. The reason I didn't was because it would make custom styling of
tables weird
To reproduce:
Add
```html
<link rel="stylesheet" type="text/css" href="https://s.brightspace.com/lib/reset-css/1.1.0/reset.css">
```
to the `<head>` of demo/index.html. Then
```
npm install
polymer serve
open http://localhost:8080/components/d2l-table/demo/
```
> Fun fact: reset.css overrides the table's border-collapse property

- d2l-scroll-wrapper.html
- d2l-table-wrapper.html
To reproduce,
open demo/simple.html or demo/index.rtl.html in Firefox/IE. Observe the tables with a scrollbar
> Fix scroll-left/scroll-right styles not working correctly on Firefox and IE

- d2l-table-wrapper.html
Wierd that polylint didn't catch this...
To Reproduce:
```shell
git clone git@github.com:Brightspace/brightspace-integration.git
cd brightspace-integration
npm install
npm run serve
```
Point an LMS at the local BSI instance. Then open UserProgress (or any page using grid) and change the page size until the horizontal scrollbar appears
To test the fix, run `bower install d2l-table#fix-minification-error` and rerun `npm run serve`
> Fix BSI minification error

- d2l-scroll-wrapper.html
* Scroll to the d2l-scroll-wrapper, and use the arrow keys
Tested with focus-able elements within the table. The table is still able to scroll with the arrow keys as expected. Tested on Chrome.
> US76169 - Hide scroll buttons, and make d2l-scroll-wrapper focusable for keyboard navigation

- d2l-scroll-wrapper.html
- d2l-sticky-element.html
* d2l-sticky-element starts off as disabled in d2l-scroll-wrapper
* Stickyfill.rebuild() will only be called when needed
> Optimize d2l-sticky-element

- d2l-scroll-wrapper.html
- d2l-sticky-element.html
- test/d2l-scroll-wrapper.html
In IE, the effect is very clear on some pages. The table gets rendered, then the border styling and sticky buttons show up. On Chrome, it's unnoticeable.
> Only calculate sticky buttons and scrollbars after page renders

- d2l-table-style.html
- demo/simple.html
* Collect similar rules, remove >:first-child, >:last-child, >:only-child rules
* 29% gains in IE11 when styles are being calculated. On the enter grades page, this is ~67ms faster for every style calc. Less CPU => happier browser => happier user
> Optimize CSS

- bower.json
* This version doesn't work with Shadow DOM, but Chrome has position:sticky implemented
Fixes #115
> Use stickyfill 1.1.4

- d2l-table-style.html
- demo/sticky-headers.html
Three fixes in this PR:
1. inner tables were inheriting styling rules from the sticky table. I modified just the rules that were causing problems on the grade_final_edit page. Some (but not all) of the rules were RTL only.
2. Jared's one-line fix
3. If a sticky header has two rows, the horizontal border between them disappears when the header is stuck. I fixed that by removing a `border-top: none`.
> fix inner table inheriting sticky styling

- d2l-scroll-wrapper.html
- d2l-table-col-sort-button.html
type=button required so that these buttons don't attempt to submit forms
from legacy pages before the page has loaded.
> DE29930 - Add type=button for column sort and scroll buttons

- d2l-scroll-wrapper.html
In some occasions in IE and Edge, there is a little deviation in the lowerScrollValue used in checkScrollThresholds for not being 0. I have seen it being 1 in IE and Edge. Resulting the scroll arrow icon being shown incorrectly when there is no overflow happening in UI. 
I am making the check value to be an attribute defaulting to zero, so people with problems can make their own fine tuning adjustment.
> added checkScrollDeltaValue attribute

- d2l-tspan-resize-observer-polyfill.js
- d2l-tspan.js
- package-lock.json
- package.json
Fixed `<tspan>` not resizing when its content changes size in non-Chrome browsers
> DE32893 -- Workaround broken ResizeObserver in Polymer 3

- d2l-scroll-wrapper.js
- d2l-table.js
There is likely a nicer way to do this, but all my attempts created larger issues so I went with this approach.
When `<d2l-table>` is used, there is no `<table>` element directly around the slotted content, so `role="table"` is added to the `d2l-table`. Unfortunately, there are too many levels between the `<d2l-table>` and the rest of the table elements, which causes some screenreader/browser combinations to not be able to see the table contents or navigate them.
This change has been tested successfully with:
- VO+Safari (iOS)
- VO+Safari (Mac)
- VO+Chrome (Mac)
- Talkback+Chrome (Android)
VO+FF (Mac) was tested, and it had slight improvement of reading the number of rows correctly, but otherwise still does not work. My understanding is this combination is not really a thing people use …
> Fix a11y of d2l-table

- demo/overrides-demo.js
- demo/overrides.html
I'm seeing an issue with overriding the css variables in table mixins (like https://github.com/BrightspaceUI/table/blob/master/d2l-table-shared-styles.js#L25), when using a Polymer 3 class-based component (the modularized components using `innerHTML` seem to work fine).  Adding a demo to highlight the problem, which currently looks like this:
The fix is pretty simple, if we're ok with moving those specific styles out of `d2l-table-shared-styles.js` and into `d2l-table-style.js`
> Add demo that shows the overrides problem

- d2l-table-shared-styles.js
- d2l-table-style.js
Moving the css variables out of the mixins.  Demo now looks like this:
Compared to (https://github.com/BrightspaceUI/table/pull/208)
> Fix table style overrides

- table.test.js
* Saves 1-2 minutes (when nothing else is running)
> Reduce galen tests duration by running longest tests first

- d2l-table-style.js
There's an interesting behaviour when sticky elements co-exist with elements positioned relatively in the same sticky container. In grades, this manifests itself because our inputs are relatively positioned:
Grades has [hacked around this](https://search.d2l.dev/xref/lms/le/grades/static/css/grade_object_render.css?r=2eebc24f#2) by overriding the `input` positioning to `static`. But this hack doesn't work with our `<d2l-input-number>` web component (which also uses relative positioning internally) because it can't pierce the shadow root.
The fix for this, as described [in this blog post](https://hackernoon.com/css-underdog-rule-position-sticky-0z2t3y7r) is to apply a `z-index` to the sticky element. Clearly this already happened somewhere because some of the sticky elements in here have a …
> Fix sticky headers with relative elements

- d2l-table-wrapper.js
- d2l-table.js
Putting `last-row` on a row in the table used to be required if there was crazy CSS hiding rows, but that functionality [was removed in early 2018](https://github.com/BrightspaceUI/table/pull/149). This just removes it from the docs so it doesn't confuse us again the next time we try to port this to something else. :)
I've remove the [usages in the LMS as well](https://search.d2l.dev/search?project=lms&full=%22last-row%22&defs=&refs=&path=&hist=&type=&xrd=&si=full&si=full) since they're also pointless.
> removing docs for last-row as it's no longer supported

- README.md
- d2l-table-style.js
- d2l-table-wrapper.js
- d2l-table.js
- demo/index.html
- demo/light.html
- demo/overrides-demo.js
- demo/simple.html
In reviewing table's variants, I noticed was that the concept of "active" rows is completely redundant as its style is identical to "selected" rows (background of Celestine+2 and border of Celestine+1). Active rows also weren't in the original design, and don't seem to serve a purpose. For those reasons, we'd like to remove the concept of "active" entirely.
There's a single usage in manager-view where they're applying both "active" AND "selected". I've [put up a pull request](https://github.com/Brightspace/manager-view-fra/pull/2087) to address that.
> feat: removing concept of "active" rows

- d2l-table-shared-styles.js
- d2l-table-style.js
- d2l-table-wrapper.js
- d2l-table.js
- demo/index.html
- demo/light.html
- demo/overrides-demo.js
- demo/responsive-demo.js
- demo/sticky-headers-demo.js
Similar to removing the concept of "active" rows, I'm also removing support for the "selectable" attribute at the table level. This attribute went on the `<table class="d2l-table" selectable>` or `<d2l-table selectable>` elements and when present it applied "selected" styles to rows when the user hovered over them.
This was again not part of the table design, and as you can see by the CSS I've removed in this PR it added a fair amount of complexity.
Plus, it only ended up getting used in one place in [public-fra](https://search.d2l.dev/xref/Brightspace/publish-fra/src/publish-packages.js?r=226464e8#398), where they're using it as a CSS selector (not an attribute) and have copied table's styles and modified them to make that work. So they won't even be impacted by this removal.
> feat: removing "selectable" functionality

- d2l-table-shared-styles.js
Tweaking the table header (both normal and light) line-height to be `0.9rem` instead of `1rem` [as per the design](http://design.d2l/components/tables/).
> fix: line-height of header cells should be 0.9rem

- d2l-table-shared-styles.js
- d2l-table-wrapper.js
- d2l-table.js
Another small tweak to align the selected row border/outline colours with the design. They should have been Celestine, not Celestine+1.
> fix: changing selected border colours to celestine

- d2l-table-col-sort-button.js
- d2l-table-shared-styles.js
- d2l-table-style.js
- d2l-table.js
When these components move to Lit, we lose support for Polymer's style mixins. So they either need to go away because they were not actually used (best case!), or instead expose CSS variables for each thing that places were overriding.
Luckily with the table mixins nothing was actually using or setting them, so they can just move to inline styles. Beyond all the places that just copy-pasted these styles verbatim, there is [one usage](https://search.d2l.dev/xref/Brightspace/insights-engagement-dashboard/components/table.js?r=2281dfce#188) where they're `@apply --d2l-table`. I looked into it though and it was just a mistake as the table styles aren't even included -- the team will be removing it shortly.
Scroll-wrapper is going to be another story entirely, which is why I'm not handling it …
> fix: replacing table style mixins with inline styles

- d2l-table-style.js
This was a regression caused by the [fix for numeric inputs](https://github.com/BrightspaceUI/table/pull/220). By applying a `z-index` of 3 to all the sticky headers, when a header itself is sticky (like when the first column is sticky), they have the same `z-index` and it no longer goes "under" the other header cells.
Problem:
The fix involves bumping that sticky header column `z-index` up by 1:
I'm hoping these types of regressions can be avoided in the future with visual diffs.
> fix: sticky first column must be above other sticky headers

- d2l-scroll-wrapper.js
- d2l-table-wrapper.js
- d2l-table.js
- demo/d2l-scroll-wrapper.html
The goal here is to remove the need for the various Polymer style mixins that `d2l-scroll-wrapper` uses. There are a lot of them, so this will take a bit.
The first three I'd like to starve out are all typically used together:
- `--d2l-scroll-wrapper-h-scroll`: applied whenever there's some form of horizontal scroll happening, and in almost every place it's used it applies a dashed right and left border
- `--d2l-scroll-wrapper-left`: applied when the scroll wrapper is scrolled all the way to the left, and typically just hides the left dashed border
- `--d2l-scroll-wrapper-right`: applied when the scroll wrapper is scrolled all the way to the right, and typically just hides the right dashed border
Here's an example of the dashed border getting applied to the right but not the left: …
> feat: showing dashed borders whenever "has-actions"

- d2l-scroll-wrapper.js
I noticed a bug when testing out other changes in engagement dashboard: when the scroll wrapper is right after an element with bottom margins, when the sticky buttons are visible the margins collapse. This results in weird spacing shifts when the buttons appear/disappear.
For example, with no overflow everything is great:
And then with overflow notice the space between the heading and scroll wrapper is gone:
I've reverted table all the way back to several months ago and the issue still persists, so it's not related to any recent changes. All I can think of is that Chrome changed margin collapse behaviour, although it's also reproducible in all the other browsers so who knows.
The fix is to just remove the margins on the sticky buttons, which appears to now be unnecessary anyway. I think …
> fix: margin collapse bug

- d2l-scroll-wrapper.js
- d2l-table.js
This kills two birds with one stone:
**1) Removes `<d2l-table>`'s usage of the `--d2l-scroll-wrapper-inner` Polymer style mixin**
There's still one more [in manager dashboard](https://search.d2l.dev/xref/Brightspace/manager-view-fra/src/table/mr-table-selectable.js?r=809d461e) that I need to sort out, but this particular usage was applying the styles we normally put on the native `<table class="d2l-table">` element -- except on scroll wrapper's "inner wrapper" `<div>`.
I worked around this by just applying those same styles to a `<div>` inside `<d2l-table>` instead.
**2) Eliminates the needs for the `needs-table` attribute on `d2l-scroll-wrapper`**
The `needs-table` attribute was only used from here to put `role="table"` on that same inner wrapper. I again moved it to a new `<div>` that …
> fix: removing d2l-table's usage of scroll-wrapper-inner

- d2l-scroll-wrapper.js
- demo/d2l-scroll-wrapper.html
In order to simplify the migration to Lit, this PR removes 4 attributes that were never set to anything other than the defaults: `scroll-amount`, `scroll-duration`, `start-icon` and `end-icon`.
I have PRs up into [GBL](https://github.com/Brightspace/gbl-map-viewer/pull/255) and [rubrics](https://github.com/Brightspace/d2l-rubric/pull/757) to remove the places they were setting them, although they were just setting them to the default so this can merge without those changes.
> fix: removing attributes which were never used

- d2l-scroll-wrapper.js
- test/d2l-scroll-wrapper.html
All usages of these style mixins have been removed [except this one](https://search.d2l.dev/xref/Brightspace/manager-view-fra/src/table/mr-table-selectable.js?r=809d461e#27) which is still being investigated by @bearfriend.
This removes the remainder, merging their styles inline.
> fix: remove unused Polymer style mixins

- d2l-scroll-wrapper.js
After speaking with Jeff, we'd like this offset to just always be `-10px`, which will actually [match the original design](http://design.d2l/components/tables/).
This variable is only used [in one place in BSI](https://search.d2l.dev/xref/Brightspace/brightspace-integration/web-components/d2l-table.js?r=bb01a27f#7), where it sets it to `-10px` -- so I'll be removing that once this releases.
> fix: make scroll wrapper action offset always 10px

- d2l-scroll-wrapper.js
- d2l-table-circle-button.js
- d2l-table-wrapper.js
- d2l-table.js
- demo/d2l-scroll-wrapper.html
- demo/responsive.html
These changes align the look of the buttons with design's original intent and have been tweaked by Jeff.
Changes:
- Horizontal offset is `10px` instead of `15px` which better matches the design and makes it look less “off centre”
- Vertical offset is `4px` instead of `10px` which centres it within the first row when used in a table
- Background colour is regolith instead of sylvite
- Border colour is mica instead of galena
- Box-shadow is the same as dropdowns (`0 2px 12px 0 rgba(0, 0, 0 0.15)`)
Before:
After:
All the variables around this are gone as well -- I'll be cleaning up the places using this afterwards.
> fix: aligning action buttons with design intent

- d2l-table-style.js
This reverts the changes made [in this PR](https://github.com/BrightspaceUI/table/pull/220) and then the follow-up regression fix [in this PR](https://github.com/BrightspaceUI/table/pull/227). Cert fix for the April release against table version `2.4.x` will follow.
When `position: sticky` is applied to an element, anything that's positioned _relatively_ will go on top of it -- like our new numeric inputs (the source of #220) or our context-menus (an existing unreported bug).
The solution to this (as done in #220) is to put a positive `z-index` on the sticky element. But that causes another issue as elements _inside_ the sticky element who wish to appear overtop of other things cannot escape. Such is the case with context-menus inside the sticky headers:
The only solution to this new …
> fix: reverting changes to z-index

- d2l-scroll-wrapper.js
Motivated by rubric printing, where scroll wrapper borders/controls were carrying over from the browser view to the printed page view, even though no scrolling was necessary (or possible) on a printed page.
Related tickets: [US125790](https://rally1.rallydev.com/#/57732444928d/custom/373260458992?detail=%2Fuserstory%2F508479614416) [US125179](https://rally1.rallydev.com/#/57732444928d/dashboard?detail=%2Fuserstory%2F502202898352)
> feat: Hide d2l-scroll-wrapper visuals when printing webpages

- d2l-table-style.js
I can't for the life of me figure out why this was needed -- it's putting `20px` of left padding on tables but only in RTL. The only outcome I can see is that tables in RTL end up being able to fit `20px` less stuff, which seems weird and wrong.
This was introduced with the initial sticky-headers stuff, so there's no history of it being added to fix something -- all I can think of is it was left in accidentally.
I'd like to remove it at this point so that when I exclude it from the Lit version it doesn't cause all the sticky+RTL visual diffs to be off.
> fix: removing RTL-only padding

- d2l-table-style.js
- d2l-table-wrapper.js
One more small set of fixes to make the visual diff tests for the Lit conversion less jarring.
These negative top/left offsets for sticky header tables exist so that when you scroll, the borders don't show through the "default" style table's rounded corners. But light tables don't have rounded corners, so applying the offsets isn't needed.
Second, for multi-row sticky headers there's logic that goes through and sets a top offset equal to the height of the first row. That calculation only ever worked for the "default" style which has a `-5px` offset and `2px` border (hence it had `3px` subtracted from it). For "light" tables, this needs to be `+1px` to compensate for the border only.
Before change (note the misaligned border and the missing border between the 1st & 2nd header row):
After …
> fix: light tables don't need offsets for rounded corners

- d2l-table-style.js
I missed one use case: using `<d2l-table-wrapper>` from inside a Polymer element. In that scenario, the styles were getting added to the root document but couldn't pierce the wrapper element's shadow root so weren't getting applied.
This change just moves them into the style `dom-module` just like the older d2l-table/d2l-tr/etc. styles.
The unfortunate side-effect of all this is that Polymer elements will need to continue to use the Polymer version of d2l-table, and Lit ones will need to use the Lit version -- no mixing and matching. So that kind of goes against how web components work... but I'm justifying it in my mind by thinking of these more as shared styles than a web component. In Polymer the way you share styles is these `dom-module`s and in Lit it's importing style literals into …
> fix: including Lit table styles in the dom-module

- d2l-tspan.js
- package.json
- polymer.json
This switches to use the native `ResizeObserver` (with polyfill for older browsers) over using the `@brightspace-ui/resize-aware` stuff. Tested using demo pages. Updated to run demos wtih `@web/dev-server` since `polymer` didn't like optional chaining stuff.
> feat: remove use of `@brightspace-ui/resize-aware`
